blog/urls.py
from django.urls import path, include
from .views import like, post_delete, post_detail, post_list,post_create, post_update

app_name = "blog"

urlpatterns = [
    path('',post_list, name='list'),
    path('create/',post_create, name='create'),
    path('<str:slug>',post_detail, name='detail'),
    path('<str:slug>/update/',post_update, name='update'),
    path('<str:slug>/delete/',post_delete, name='delete'),
    path('<str:slug>/like/',like, name='like'),
    path('users/',include("users.urls"))
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) : Geliştirme aşamasında benim media file larımı gösterdiğim yerden kullan, canlıya çıktığımda başka ayar yapacağım

users/urls.py
import imp
from importlib import import_module
from re import template
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import register,profile
from .forms import PasswordResetEmailCheck

app_name = "users"

urlpatterns = [
    # biz django.contrib.auth import views as auth_views i komple aldık, bunun içinden istediğimizi alacağız
    # name : login olmak zorunda gereklilik
    path('login', auth_views.LoginView.as_view (template_name="users/login.html"), name='login'),
    path('logout', auth_views.LogoutView.as_view(
        template_name="users/logout.html"), name='logout'),
    path('register/', register, name='register' ),
    path('profile/', profile, name='profile'),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name="users/password_reset_email.html", form_class=PasswordResetEmailCheck) , name='password_reset'),

    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html"), name='password_reset_done'),

    path('password-reset/confirm/<uuid64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html"), name='password_reset_confirm'),

    path('password-reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/main.css'%}">
    <title>Marcus Blog</title>

</head>
<body class="">
    {% include 'main/navbar.html' %}
            <div class="container">
      
                {% if messages %}
                
                {% for message in messages %}
                
                  <div class="alert alert-{{message.tags}}">
                      {{message}}
                  </div>
                  
                {% endfor %}
                      
                {% endif %}
            </div>

    <div class="container">
    This is base html <hr>
    {% block content %}
        
    {% endblock content %}
      </div>  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/9dee1d57df.js" crossorigin="anonymous"></script>
</body>
</html>

templates/main/navbar.html
<header class="site-header">
    <nav class = "navbar navbar-expand-md navbar-dark  bg-steel fixed-top">
        <div class="container">
            <a href="(% url 'blog:list' %)" class="navbar-brand mr-4">Marcus Blog</a>
            <button class = " navbar-toggler " type="button" data-toggle ="collapse" aria-controls = "navbarToggle " data-target = "#navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class = " navbar-toggler-icon "></span>
            </button>
            <div class = " collapse navbar-collapse " id = "navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a href="{%url 'blog:list' %}" class="nav-item nav-link">Home</a>
                    <a href="#" class="nav-item nav-link">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">

                    {% if user.is_authenticated %}

                        <a class="nav-item nav-link" href="{%url 'users:logout' %}"> Logout </a>
                        <a class="nav-item nav-link" href="{%url 'users:profile' %}> Profile </a>
                        <a class="nav-item nav-link" href="{%url 'blog:create' %}"> New Post </a>

                    {% else %}

                        <a class="nav-item nav-link" href="{%url 'users:login' %}"> Login </a>
                        <a class="nav-item nav-link" href="{%url 'users:register' %}
                    {% endif %}


    

                </div>

            </div>

        </div>
    </nav>
</header>