blog/urls.py
from django.urls import path, include
from .views import like, post_delete, post_detail, post_list,post_create, post_update

app_name = "blog"

urlpatterns = [
    path('',post_list, name='list'),
    path('create/',post_create, name='create'),
    path('<str:slug>',post_detail, name='detail'),
    path('<str:slug>/update/',post_update, name='update'),
    path('<str:slug>/delete/',post_delete, name='delete'),
    path('<str:slug>/like/',like, name='like'),
    path('users/',include("users.urls"))
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) : Geliştirme aşamasında benim media file larımı gösterdiğim yerden kullan, canlıya çıktığımda başka ayar yapacağım

blog/models.py
from distutils.command.upload import upload
from email import contentmanager
from email.mime import image
from email.policy import default
from importlib.resources import contents
from multiprocessing import AuthenticationError
from tabnanny import verbose
from turtle import title
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#media yüklendiğinde media nın içinde blog oluşturaacak 0 yerine id si ile , 1 yeride ise dosya ismi ile bir klasöt oluşturup içine atacak
def user_directory_path(instance, filename):
    return 'blog/{0}/{1}.format(instance.author.id, filename)'


class Category(models.Model):
    name = models.CharField(max_length=100)
# Burası admin panelde Categorys görünmesi yerine Categories olarak  görünmesi için
    class Meta:
        verbose_name_plural = 'Categories'
# Burası admin panelde veya ilk çağırılan yerde default hangi başlığın görüeceğini tespit eder
    def __str__(self):
        return self.name



class Post(models.Model):
    OPTIONS = (
        ('d', 'Draft'),
        ('p', 'Published')
    )
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to=user_directory_path, default='smileicon.jpg')
    category = models.ForeignKey(Category, on_delete=models.PROTECT )
    publish_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=OPTIONS, default='d')
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title
    
    def get_comment_count(self):
        return self.comment_set.all().count()

    def get_view_count(self):
        return self.postview_set.all().count()

    def get_like_count(self):
        return self.like_set.all().count()

    def comments(self):
        return self.comment_set.all()



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    time_stamp =  models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.user.username


class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

blog/forms.py
from pyexpat import model
from socket import fromshare
from django import forms
from .models import Category, Post,Comment


class PostForm(forms.ModelForm):
    status = forms.ChoiceField(choices=Post.OPTIONS)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Select')
    class Meta:
        model = Post
        fields = (
            'title',
            'content',
            'image',
            'category',
            'status',
        )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

blog/views.py
from http.client import HTTPResponse
from multiprocessing import context
from tkinter import N
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CommentForm, PostForm
from .models import Like, Post
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.


def post_list(request):
    qs = Post.objects.filter(status="p")
    context = {
        "object_list":qs
    }
    return render(request, "blog/post_list.html", context)

@login_required()
def post_create(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
    # form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            #şimdi user kimse o author olacak. form objesini kaydet ama database e gönderme diyoruz
            post = form.save(commit=False)
            print(request.user)
            post.author = request.user
            post.save()
            messages.SUCCESS(request, "Post created succesfully")
            # urls'e  app_name = "blog"  ekleyerek hangi appteki list olduğunu belirlemiş olduk
            return redirect("blog:list")
    context = {
        'form':form
    }
    return render(request, "blog/post_create.html",context)


def post_detail(request, slug):
    form = CommentForm()


    print("request.user : ", request.user)
    print("request : ", request)
    # print("request.get : ", request.get)

    obj = get_object_or_404(Post, slug = slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid:
            print("request.user : ",request.user)
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = obj
            comment.save()
            return redirect("blog:detail", slug=slug)
    context = {
    'object':obj,
    'form' :form
    }
    return render(request, "blog/post_detail.html",context)


@login_required()
def post_update(request,slug):
    #Post.objects.get(slug=lerafsdf-dgdfg-fghfg-h )
    obj = get_object_or_404(Post, slug=slug) # bu slugtakileri bul bana  listele demek
    #if req pos ise yerine bunu kullandık
    if request.user.id != obj.author.id:
        messages.WARNING(request, "You r nor a author of this tag")
        return redirect("blog:list", slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        form.save()
        messages.SUCCESS(request, "Post updated succesfully")
        return redirect("blog:list")
    context={
        "object":obj,
        "form":form
    }
    return render(request, "blog/post_update.html", context)


@login_required()
def post_delete(request,slug):
    obj = get_object_or_404(Post, slug=slug)
    if request.user.id != obj.author.id:
        return HTTPResponse('You are not authorized !')
    if request.method == "POST":
        obj.delete()
        messages.SUCCESS(request, "Post deleted succesfully")
        return redirect("blog:list")
    context = {
        "object": obj,
        }
    return render(request, "blog/post_delete.html", context)


@login_required()
def like(request, slug):
    if request.method == "POST":
        obj = obj = get_object_or_404(Post, slug=slug)
        # artık hangi posta like yapacağımı biliyorum
        like_qs = Like.objects.filter(user=request.user, post=obj)
        if like_qs.exists():
            like_qs[0].delete()
        else:
            Like.objects.create(user=request.user, post=obj)
        return redirect("blog:detail", slug=slug)
    return redirect("blog:detail", slug=slug)

templates/blog/post_create.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- picture upload ederken bunu yazmalıyız -->
<form class="uniForm" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    
<button type="submit">Send</button>


</form>
    
{% endblock content %}
    

templates/blog/post_delete.html
{% extends 'main/base.html' %} 


{% block content %}
  
<p>Are you sure delete {{object.title}}</p>
   <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <button type="submit"><a href="{%url 'blog:list'%}">Cancel</a></button>
        <button type="submit">Yes</button>

    </form>
{% endblock content %}

templates/blog/post_detail.html
{% extends 'main/base.html' %} 


{% block content %}
  
    <h1>Details page</h1>
        <h1>{{object.title}}</h1>
        <img src="{{object.image.url}}" alt="" srcset="" />
        <p>{{object.content}}</p>
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <button type="submit" class="btn btn-primary">Comment</button>
        </form>
        <br>
        {% for comment in object.comments %}
            <hr>
            <p>comment by {{user}}</p>
            <p>{{comment.content}}</p>
            
        {% endfor %}
        <form action="{% url 'blog:like' object.slug %}" method="POST">
            {% csrf_token %}
            <input type="hidden", name="post">
            <input type="hidden", name="user">
            <button type="submit">Like</button> {{object.like_count }}

        </form>
            <br>
            
            {% if user.id == object.author.id %}
                <button class="btn btn-danger"><a href="{% url 'blog:delete' object.slug %}"></a>delete</button>
                <button class="btn btn-primary"><a href="{% url 'blog:update' object.slug %}"></a>update</button>
                
            {% endif %}
                
   
{% endblock content %}

templates/blog/post_list.html
{% extends 'main/base.html' %}


{% block content %}
<h1>Post List Page</h1>
<div class="row mt-5">
    {% for object in object_list %}
    <div class="col-4">
        <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 18rem; height:25rem">
            <img src="{{object.image.url}}" class="card-img-top" alt="post_image" >
            <hr>
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'blog:detail' object.slug %}">{{object.title}}</a></h5>
                <p class="card-text">{{object.content|truncatechars:50}} </p>
                <p>
                    <span><i class="far fa-comment-alt ml-2"></i>{{object.get_comment_count}} </span>
                    <span><i class="fas fa-eye ml-2"></i>{{object.get_view_count}} </span>
                    <span><i class="far fa-heart ml-2"></i>{{object.get_like_count}} </span>
                    <p class="card-text"><small>Posted{{object.publish_date|timesince}} ago.</small></p>
                </p>
            </div>
        </div>
    </div>
   
  {% endfor %}
    
</div>
  {% endblock content %}



    

templates/blog/post_update.html
{% extends 'main/base.html' %} 
{% load crispy_forms_tags %}

{% block content %}
  
    <h2>Update {{object.title}}</h2>
<form class="uniForm" action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form|crispy}}
<button type="submit">Update</button>

{% endblock content %}